### ISSUE TITLE
Epic: Create an Initial gRPC Client/Server Model

### ISSUE THREAD

**Issue by JarrodCarson** [mamaluigie/API-Interface-Tool#8]
Create the initial gRPC Client/Server Model

Tasklist:
- [ ] Install and configure gRPC and Protocol Buffers for Python
- [ ] Setup Protocol Buffer objects and methods for RPC interaction
- [ ] Set up a simple client and server to test gRPC communication
- [ ] Implement unit tests in Pytest for client and server communication
